name: lab10zad2.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
    - name: Check out to repo
      uses: actions/checkout@v4

    - name: Get version
      run: echo "version=$(sed -n 's/.*<p>\(.*\)<\/p>.*/\1/p' index.html)" >> "$GITHUB_ENV"

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup buildix
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: michalmigryt/lab10image:${{ env.version }}

  kubernetesCI:
    needs: dockerCI
    runs-on: ubuntu-latest

    steps:
      - name: Check out to repo
        uses: actions/checkout@v4
        with:
          repository: michal-migryt/Config-repo
          token: ${{ secrets.CONFIG_TOKEN }}
      - run: |
          sed -i 's/michalmigryt\/lab10image:.*/michalmigryt\/lab10image:${ needs.dockerCI.env.version }}/g' deployment.yaml
          git config user.name action_user
          git config user.email action_user@example.com
          git add -u
          git commit -m "app update v${{ needs.dockerCI.env.version }}"
          git push
